version: '3.8'
services:
  judge0:
    image: judge0/api:1.13.1
    ports:
      - "2358:2358"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - DB_USER=judge0
      - DB_PASSWORD=yourpassword
      - DB_NAME=judge0
      - JWT_SECRET=secret
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.2

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: yourpassword
